title: VSISLab
description: > # this means to ignore newlines until "baseurl:"
  Train your network and then submit your result.

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed
theme: cayman
